### PR TITLE
Dropped support for py26 & Django 1.4, 1.5 1.6, 1.7, added 1.9, 1.10

### LINKED ISSUE #67: Remove django < 1.8 support

### PR DESCRIPTION
**Pull request by ewjoachim**
Closes #67, #68, #69 
Ping @zebuline . @wo0dyn ?

### CODE REVIEW

**Comment by ewjoachim** [comment]
Forgot traviiiis :D

**Comment by ewjoachim** [comment]
Oh, BTW, is it acceptable to drop Py3.3 that is deprected on next september ?

**Comment by wo0dyn** [comment]
> Oh, BTW, is it acceptable to drop Py3.3 that is deprected on next september ?

Looks like Travis has been silly with new PRs for awhile. I tried to work on #66 and I didn't quite understand what was going on. The PR LGTM but tests are failing.

**Comment by Natim** [comment]
> is it acceptable to drop Py3.3 that is deprected on next september ?

IMHO, it is. I wouldn't run Python3.3 in production without upgrading it to at least Python 3.4

**Comment by Natim** [comment]
`ImportError: No module named demo.settings`
I have no idea of why...

**Comment by Natim** [comment]
I guess it still needs more work to support 1.10 on Python3.

```
    from django.conf.urls import patterns, include
ImportError: cannot import name 'patterns'
```

**Pull request merged**
