### PR TITLE
Add python 3.5 support

### PR DESCRIPTION
**Pull request by Natim**
cf https://github.com/novafloss/django-mail-factory/blob/master/tox.ini#L3:L6

### CODE REVIEW

**Comment by zebuline** [comment]
oups, I wanted to create a ticket :)

**Comment by Natim** [comment]
You did create a ticket actually :)

**Comment by zebuline** [comment]
thank you for the troll @Natim :)
and for the PR :p

**Comment by Natim** [comment]
Apparently tests doesn't run anymore there...

**Comment by wo0dyn** [comment]
> @wo0dyn could you take a look when you have time ? :)
> — @zebuline 

Yeah, sure — cc @Natim

**Comment by Natim** [comment]
@wo0dyn Don't hesitate to iterate on my branch :)

**Comment by wo0dyn** [comment]
Sorry guys! :worried: Tab's still opened on my browser; I didn't take the time to get back on this.

**Comment by ewjoachim** [comment]
Up ? @wo0dyn :D

**Comment by wo0dyn** [comment]
Addressed in #70. I'm closing this PR.
Thanks @Natim and @ewjoachim. :wink:

**Pull request closed without merging**
