### PR TITLE
Using absolute imports (was relative imports)

### PR DESCRIPTION
**Pull request by benoitbryon**
Based on #49

### CODE REVIEW

**Comment by benoitbryon** [comment]
@yanoz: it looks like project's authors (@magopian and @Natim) don't have permissions on this Github repository. Can you grant them admin privileges on this repo?

**Comment by yanoz** [comment]
nop... we already discussed that few monthes ago. No solution has been validated nor implemented. 
Thing is, I don't want to add @magopian and @Natim as member of Novapost organization.
An idea was to create Novapost OSS organization.
You tell me. Of course my point is not to "close" the project. 
@rodo @lisael your idea?

**Comment by Natim** [comment]
Hopefully github has got another solution for you. It is to set collab people on a project basis so you do not need to create another organisation.

The thing is it was the case on this project last time we checked it and today I wanted to restart the travis for this PR and I was not allowed anymore.

I don't understand what prevent you from adding some contributors to the project they are still maintaining? Why don't you put them private if you don't want the community to help improve them?

**Comment by rodo** [comment]
@Natim it seems that you misunderstood the problem, we want to open projects and in first maintain orginal contributor/maintainer, but we can't include external people in corporate organization, sure you understand these point. If the old way things were done does'nt work (it's the case when you loose your rights) we have to change them, a new organization called something like NovaFloss or other may be a good ideau, this organization will contain all public projects. 
I need more information in why just stand alone project does'nt work for us ? Why do we need to keep django-mail-factory and other project under Novapost organization ?

**Comment by yanoz** [comment]
"Of course my point is not to "close" the project. "
Please, read carefully before writing stupid things.

**Comment by Natim** [comment]
> but we can't include external people in corporate organization, sure you understand these point

No that's exactly the point.

> Why do we need to keep django-mail-factory and other project under Novapost organization ?

I am not at Novapost anymore so I wont argue more than this statement about this.
If you want to create a new org for opensource project that's a solution but here is why I think it is not a good solution:

 - Having all project in the same organisation is easier for Novapost workers because they don't have to think about if it should be a public project or not upfront, they can start it private and discover later that it can be made public
 - Having all project under the novapost organization helps the community to decide if the project is worth using. It is a also a good advertisement for the Novapost / Peopledoc brand 
 - Having another organisation is fine I think but it will bring the same problems as for the novapost organisation because you will have more rights managements to do (adding people on both orgs) and you will still need to define collab on a per project basis (because all collaborators should not be able to commit on all projects)

> "Of course my point is not to "close" the project. "

I never said such a thing.

**Comment by yanoz** [comment]
lol, no I did.
So I'm a bit pissed of you could say such crap
>  Why don't you put them private if you don't want the community to help improve them?

Again, I won't add you as Novapost organization member. That's a fact. 
Let's find another solution.

**Comment by Natim** [comment]
>  I won't add you as Novapost organization member

This is not what I ask for.

I was thinking about: https://help.github.com/articles/adding-or-inviting-members-to-a-team-in-an-organization/

If you create a team per project it will let you give access to this project to some people that are not members of the Novapost organization.

If you want we can host public project with external collab on the spiral-project org.

**Comment by rodo** [comment]
> Having all project in the same organisation is easier for Novapost workers because they don't have to think about if it should be a public project or not upfront, they can start it private and discover later that it can be made public

You make me scared, you don't start by reading the licence before contribute to a project ?

More seriously be sure we work hard to find the best solution, I'll read about Github Teams, I discover this github functionnality, thanks for that. I always worked on public project I'm not comfortable when I have to close doors.

**Comment by Natim** [comment]
> You make me scared, you don't start by reading the licence before contribute to a project?

All project starts private (Authorship) until you put a Licence on them.

**Comment by yanoz** [comment]
But you're ok that if you become member of this specific project's team, then you become member of Novapost Organization, right?

**Comment by Natim** [comment]
You mean that our pictures may appear on the first page of the organization?
Apparently yes but we will have only rights of the teams we are on.

I don't understand what is your definition of organization's member.

**Comment by benoitbryon** [comment]
What truly matters is PyPI and readthedocs. Code repository can be moved. So at Novapost we should not block project development because of permissions on code reporitory. It is "_fix permissions_" VS "_move repository_".

Nobody at Novapost owns this project on PyPI or readthedocs... so at the moment Novapost cannot pretend to actually maintain the project.
Authors can upload to readthedocs and PyPI, but they don't have permissions on code repository.
Weird.

> I won't add you as Novapost organization member. That's a fact.
> Let's find another solution.

@Natim, @magopian: in the case Novapost does not implement another solution (novafloss, teams or whatever) quick enough (your appreciation), then you _can_ (that's another fact) clone the repository in a place you own, change repository URL in docs+setup.py, then update PyPI and readthedocs. Imho you may not wait for months again.

**Comment by Natim** [comment]
> In the case Novapost does not implement another solution (novafloss, teams or whatever) quick enough (your appreciation), then you can (that's another fact) clone the repository in a place you own, change repository URL in docs+setup.py, then update PyPI and readthedocs. Imho you may not wait for months again.

Yes but we love Novapost too much for that. I prefer to take the time to solve this problem and let Novapost own her projects than to fork and take control. Also I will add people that want to release new version as soon as we find a solution.

If the solution is create a new org, @yanoz it is your call and that's not really my problem. I just say I won't do that for the reasons I explained earlier. But if you think it is more important that people doesn't see my face on the Novapost organization page, then I don't have anymore arguments.

**Comment by yanoz** [comment]
It's very funny because I thought (I was wrong...) that you @benoitbryon  would be one of the person that would have helped us to find a good solution to fix this problem...

**Comment by Natim** [comment]
I rather think it is in fact a good move to make sure the conversation keep going in the right direction with all the arguments on the table.

**Comment by benoitbryon** [comment]
Enough solutions have been mentioned to stop discussing and actually do something.
I don't have enough permissions at Novapost organization to actually implement one of them.

**Comment by yanoz** [comment]
>  But if you think it is more important that people doesn't see my face on the Novapost organization page, then I don't have anymore arguments.

well... let's end this dicussion on this clever remark. We'll find a solution and we will notify you when it's done.

**Comment by Natim** [comment]
Cool thanks.

**Comment by rodo** [comment]
@Natim please let us share a beer at Fosdem to exchange on this, I need your github's knowledge on team, @magopian indeed if you are in Brussels this week end too I'll enjoy to see you at the table.

**Comment by Natim** [comment]
Yes it will be my pleasure, plus I owe some beers to @boblefrag for its Django book.

**Comment by Natim** [comment]
@benoitbryon I added you on pypi as owner of the project as well as @hobbestigrou as maintainer.

**Comment by jpic** [comment]
Sorry for closing this, but it's way to old, please re-open if this still matters to you.

**Pull request closed without merging**
