### PR TITLE
Release 0.18

### LINKED ISSUE #71: render() must be called with a dict, not a Context.
Hello!

We're currently upgrading to django 1.9 & then 1.10.
django-mail-factory is said to be django 1.10 ready, but I still get a deprecation warning:

/site-packages/mail_factory/mails.py:96: RemovedInDjango110Warning: render() must be called with a dict, not a Context. 
It seems you're still using the Context class, to render the templates, which is no more supported in django 1.10 and "works by accident". 
Ref:
https://github.com/django/django/blob/stable/1.9.x/django/template/backends/django.py#L65

Since you dropped the Dj1.7 support I guess you could just get rid of the Context class =)

Let me know if I can help, thank you for your hard work!

### PR DESCRIPTION
**Pull request by wo0dyn**
This release fixes #71.

### CODE REVIEW

**Comment by Natim** [comment]
Strange to have both commit in the same PR 🇼🇸

**Comment by wo0dyn** [comment]
> Strange to have both commit in the same PR

Ah? We always do this process everytime everywhere. :confused: 
The PR should be reviewed commit by commit though.

**Comment by Natim** [comment]
Are you using zest.releaser? You can do the following:

1. use the ``prerelease`` to create the first commit
2. File the PR and have it reviewed.
3. Merge it
4. Run `release` to release the package
5. Run `postrelease` to commit the last commit and push it with the tag

**Comment by wo0dyn** [comment]
@Natim Yes, I used `zest.releaser`. OK for this process. But that means you have to push a commit on master without a PR.

**Comment by Natim** [comment]
> But that means you have to push a commit on master without a PR.

Yes but it is an automatic one, that you can have reviewed today for all of them.

**Comment by wo0dyn** [comment]
> Yes but it is an automatic one, that you can have reviewed today for all of them.

OK. Will do :)

**Pull request merged**
